services:
  db:
    image: postgres:16-alpine
    container_name: freshrss-db
    environment:
      - POSTGRES_DB=freshrss
      - POSTGRES_USER=freshrss
      - POSTGRES_PASSWORD=oimate6777
    volumes:
      - freshrss_pgdata:/var/lib/postgresql/data
    networks:
      - freshrss-net
    restart: unless-stopped
    logging:
      options:
        max-size: 10m

  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    depends_on:
      - db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ./freshrss/config:/config
      - ./freshrss/config/custom-cont-init.d:/custom-cont-init.d:ro
    ports:
      - "127.0.0.1:5980:80"
    networks:
      - freshrss-net
    restart: unless-stopped
    logging:
      options:
        max-size: 10m

  rss-proxy:
    build: ./rss-proxy
    container_name: rss-proxy
    environment:
      - WEBSHARE_API_KEY=f626d4cbddf113cbf26e2336af8c85f73913062f
      - PORT=3000
    networks:
      - freshrss-net
    restart: unless-stopped
    logging:
      options:
        max-size: 10m

networks:
  freshrss-net:

volumes:
  freshrss_pgdata:
